import argparse

def get_config():
    parser = argparse.ArgumentParser(description='Train UNet++ on thyroid dataset')
    parser.add_argument('--train_image_dir', type=str, default='data/processed/train/image', help='Path to training images')
    parser.add_argument('--train_mask_dir', type=str, default='data/processed/train/mask', help='Path to training masks')
    parser.add_argument('--val_image_dir', type=str, default='data/processed/val/image', help='Path to validation images')
    parser.add_argument('--val_mask_dir', type=str, default='data/processed/val/mask', help='Path to validation masks')
    parser.add_argument('--test_image_dir', type=str, default='data/tn3k/test-image', help='Path to validation images')
    parser.add_argument('--test_mask_dir', type=str, default='data/tn3k/test-mask', help='Path to validation masks')
    parser.add_argument('--mask_suffix', type=str, default='.jpg', help='Suffix for mask files')
    parser.add_argument('--backbone', type=str, default='resnet34', help='Backbone for Encoder')
    parser.add_argument('--dropout_rate', type=float, default=0.2, help='Dropout rate')
    parser.add_argument('--batch_size', type=int, default=32, help='Batch size')
    parser.add_argument('--num_epochs', type=int, default=50, help='Number of epochs')
    parser.add_argument('--learning_rate', type=float, default=1e-4, help='Learning rate')
    parser.add_argument('--warmup_lr_init', type=float, default=3e-6, help='Initial learning rate for warmup')
    parser.add_argument('--device', type=str, default='cuda', choices=['cuda', 'cpu'], help='Device to use')
    parser.add_argument('--num_workers', type=int, default=4, help='Number of workers for data loading')
    parser.add_argument('--log_dir', type=str, default='logs/unetpp', help='Directory for log files')
    parser.add_argument('--checkpoint_dir', type=str, default='checkpoints/unetpp', help='Directory for model checkpoints')
    parser.add_argument('--save_interval', type=int, default=5, help='Save model every N epochs')
    parser.add_argument('--patience', type=int, default=10, help='Number of epochs to wait for early stopping if no improvement')
    parser.add_argument('--model', type=str, default='unetpp', choices=['unet', 'unetpp','deeplabv3'], help='Tên mô hình để khởi tạo')
    parser.add_argument('--pred_dir', type=str, default=None, help='Path to directory containing predicted masks')
    parser.add_argument('--num_images', type=int, default=5, help='Number of images to visualize')
    parser.add_argument('--show', action='store_true', help='Show plots instead of saving')
    parser.add_argument('--warmup_epochs', type =int ,default=10, help='Số epoch warmup')
    parser.add_argument("--csv_file", type=str, default=None, help="Đường dẫn file log csv (ưu tiên nếu có)")
    parser.add_argument("--save_dir", type=str, default=None, help="Thư mục lưu ảnh (mặc định: <log_dir>/curves/)")
    parser.add_argument('--random_order', action='store_true', help='Display images in random order')
    parser.add_argument('--seed', type=int, default=42, help='Random seed')
    args = parser.parse_args()
    return args